# theortical solution for potential and field generated by a Gaussian charge distribution
@inline function gaussian_laplace3d_pot(center::NTuple{3, T}, target::NTuple{3, T}, sigma::T) where T
    r = norm(target .- center)
    return erf(r / (sqrt(2) * sigma)) / r / 4π
end

@inline function gaussian_laplace3d_grad(center::NTuple{3, T}, target::NTuple{3, T}, sigma::T) where T
    r_vec = target .- center
    r = norm(r_vec)
    grad_f = ForwardDiff.derivative(r -> erf(r / (sqrt(2) * sigma)) / r, r)
    return grad_f .* r_vec ./ (4π * r)
end

function Rhs_dielectric_box3d_gaussian(interface::DielectricInterface, center::NTuple{3, T}, sigma::T, eps_src::T) where T
    rhs_analytic = zeros(num_points(interface))
    for (i, p) in enumerate(eachpoint(interface))
        target = p.panel_point.point
        normal = p.panel_point.normal
        rhs_analytic[i] = dot(gaussian_laplace3d_grad(center, target, sigma), normal)
    end
    return rhs_analytic ./ eps_src
end